### ISSUE TITLE
Make Twinkles Approachable

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#199]
We want to make it easier for outsiders/new users to see what is going on here, so that we can a) make it easy for them to make contributions to the project and b) keep track of things ourselves. Here's what we need to do:
- [x] Tend the issues, to make sure they are well organized #193 
- [ ] Make a few demos to get people started, whatever that means
  - [ ] Beta test the demos #182  
- [x] Have the front page (and other markdown docs) make navigating the project easy #207 
- [ ] Improve our documentation, and keep it up to date:
  - [x] DM Stack installation #160 
  - [ ] Sphinx-able API documentation https://github.com/DarkEnergyScienceCollaboration/Monitor/issues/33
- [x] Work with the Project to make sure DM tools are easy to use #190 
- [x] Make talk slides for the Oxford meeting #270 

At some point we will want to advertize this project to the collaboration much better - perhaps as a way of 
getting experience with the LSST stack (including both afw and sims), or to see how various other things work. We'll want things in good shape, and well tested, before we do this.

**Comment by drphilmarshall** [comment]
I'm going to declare victory on this. The getting started notes #207 are still not perfect but we can work on that without having this hanging around.
