### ISSUE TITLE
Epic: Getting Started at Twinkles

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#207]
OK, we need a short tutorial page to help new people get oriented with the project, and then start using and then contributing to the Twinkles codebase. 
- [x] Start something and link to it from the README #208
- [x] Tour of the Twinkles Issues
- [x] Installing the DM Stack and Twinkles package #160 
- [ ] Getting your environment set up correctly #289  
- Running the demos (sic)
- [x] Clean up the website home page #291 

Epic.

**Comment by drphilmarshall** [comment]
Closing out - I'll get back to the getting started notes when I next try and contribute analysis...
