### ISSUE TITLE
Create an accessible small data repository for tests

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/Twinkles#213]
The outputs of DM processing are kept in a data repository which has a particular structure that is defined in a mapper file. For our run1 having 985 visits, this is a large-ish repository with ~385 gigs of data. This makes it hard to work on computers with small hard drives. This is even harder if we want to run unit tests in a continuous integration system as the data must be donwloaded into the machine and tested.

We can have a script that creates a subset of the data repository in terms of a list of visits. I have added such a script in the https://github.com/DarkEnergyScienceCollaboration/Twinkles/pull/212 . But having visits corresponding to ~ 5 makes a 1GB repo. This is fine for use on a laptop, but we cannot load the Twinkles repository with this, and so the tests need to obtain the data from a different source using the install script.

There was a suggestion of trimming catalogs to make the subset repository (subrepo?) small. I do not know a good way of trimming the fits images in  a consistent way, talked to @SimonKrughoff about this and he did not think there was a very simple way either. For unit tests DM and SIMS have to deal with these large repositories and so they put them in  separate github  repositories (preferably with git-lfs). github allows 1 GB size repos, git-lfs allows more but it requires money. So, I see three alternatives for us:
- put this in a github repository separately (I can do this today, but don't think this is a good enough long term solution. we are already at the edge with 5 visits and we may need to have more to make sense of tests. The situation may be better if zipping provides a good compression.)
- put this in a git-lfs repository (will need money)
- Have a website (either commercial or DESC/ DESC team member owned) that will provide a public download in the install script 
  Steps:
- [x] Have script to make useful subsets specific to visits
- [x] Explore compression gains zipping
- [ ] Decide on where we should put the data for unit tests

**Comment by rbiswas4** [comment]
I checked that zipping the data with a tar zips it down from ~1 G to ~< 500 MB. So, I can see us putting in 10 ish visits for 1 G.

**Comment by drphilmarshall** [comment]
Hmm - where to put the data for unit tests... For now, I guess your own `public_html` directory would work - or dropbox perhaps. Is 1Gb really the smallest possible dataset to enable unit tests? I would think we could go quite a lot smaller than that (depending on the tests of course). Which test are you working to?

**Comment by rbiswas4** [comment]
Since we are using something closer to Jenkins anyway right now, maybe this is not an issue right now. Closing for now.
