### ISSUE TITLE
Image differencing recipe

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#248]
The DM Level 2 processing recipe now lives in a separate cookbook file, `doc/Cookbook/DM_Level2_Recipe.md`. This is where we need to add in a section describing how to carry out the image differencing, DIASource and DIAObject generation, and then the forced photometry that will give us our final light curves.

**Comment by SimonKrughoff** [comment]
I spent a little time looking at diffim.  Below is a first cut at this using the test data I have on disk.  This is by no means a finished thing, but it shows it's possible.  This is differencing within a night, so it should be empty.  You can see residuals around bright stars. 

Things I ran into:
- [ ] calexp PSF can be a different size form the matching PSF which causes an exception
- [ ] There is no good way to select which images should go in the template image.
- [ ] There are some issues with edges that I think are causing lots of false positives.

![image](https://cloud.githubusercontent.com/assets/945715/15615126/5a4646c6-23f1-11e6-9c18-e31644b0de5e.png)

**Comment by drphilmarshall** [comment]
@SimonKrughoff I saw from last week's meeting notes that you have since made a difference image using a Coadd as the reference. Is it true? :-) Interested to hear what additional PSF issues you ran into. Where are you keeping notes on your work? I don't see any new commits on the [DM Level 2 cookbook recipe](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Cookbook/DM_Level2_Recipe.md), nor any new files in the Cookbook folder. I haven't put image differencing on today's agenda but if you'd like to check in and ask for help/guidance/feedback please do add an item [here](https://docs.google.com/document/d/1NfIO08uqdncbApLkJyAH-UDEpA25lWCU9s26jjdd5jo/edit#heading=h.jqpckcxhia3u). Thanks! Hope all's well up there.

**Comment by drphilmarshall** [comment]
Hey @SimonKrughoff , on Tuesday @jchiang87 and I spent an hour with [Barak Zackay (Weizmann Institute)](https://www.researchgate.net/profile/Barak_Zackay) who has been writing papers on optimal image subtraction and coaddition. He made a convincing case to us that we should be making "Kaiser coadds" for use as reference images, and then using the "ZOGY corrected Alard & Lupton" scheme that is in the stack (that is, unless the ZOGY algorithm is not coded there as-is). Does this make sense to you? 

I don't think you've started work on a new image differencing section of the [Level 2 Cookbook recipe](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Cookbook/DM_Level2_Recipe.md) yet, but when you do, noting how we can summon these particular algorithms seems desirable. Interested to hear what you and @wmwv think!

**Comment by SimonKrughoff** [comment]
I believe we are going to start work on the ZOGY difference imaging technique immediately.  The coadd algorithm is actually strictly the responsibility of the Princeton group.  We could take on a prototype implementation within DESC, but I don't think I have the time for it.

**Comment by drphilmarshall** [comment]
The [image differencing recipe](https://github.com/LSSTDESC/Twinkles/blob/master/doc/Cookbook/Coadd_Diffim_Recipe.md) is now in place - let's close this out, and then issue tweaks to it separately. Nice work, Simon!
