### ISSUE TITLE
Becoming able to generate phoSim instance catalogs at SLAC

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#320]
Getting to the point where we can make instance catalogs at SLAC is an Epic task, and must be completed before Run 3 can begin. 

To do list:
- [x] #246 Upgrade Cookbook to enable instance catalog generation at SLAC
- [x] #134 Get connected to UW
- [x] #305 Write an instance catalog generation task
- [x] #313 Prepend instance catalog generation to phosim pipeline task as a "pre-burner"

**Comment by danielsf** [comment]
Update on the question of fatboy accessibility during the weekend of October 1:  UW IT does not intend to start powering down servers until Saturday, October 1, so fatboy will be on-line and available Friday, September 30.  They expect everything should be returned to normal by 8am PDT on Monday October 3 (but, as they like to remind us, there is never any guarantee with big computing systems).

**Comment by drphilmarshall** [comment]
Tom completed this, star that he is.
