### ISSUE TITLE
Run 3 Science Inputs

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#321]
Epic: decide on final choices for SN and SL samples, and make sure instance catalogs are prepared correctly. Some of the issues are old and could be closed in favor of the newer ones, the checklist here errs on the complete side.

- [x] Avoid using the same CatSim galaxies for both SNe and lensed AGN #139 
- [x] Run 1 Risk: SNe may not make good CoaddSources #146
- [x] What SN Rate should we use for the next Twinkles Run? #241 
- [x] Match Sprinkled AGN on magnitude #309 
- [x] OM10 lens galaxies all have 1" effective radius #120 
- [x] Sprinkle foreground lensing galaxies based upon match to Catsim mass and redshift #310 
- [x] Double check that quad lensing systems are present in instance catalogs  #311
- [x] Review PhoSim pipeline to avoid "pilot error" #323
