### ISSUE TITLE
Run 3 Pipeline Review Checklist

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#332]
Materials to be reviewed are as follows - if your name is mentioned, could you please provide links under your bullet point to files that reviewers should read, please?
- [x] Sims Cookbook Recipe (Authors: @danielsf, @SimonKrughoff)
  - https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Cookbook/Sims_phoSimGen.md

---
- [x] Input catalog generation code (catalogs include catsim instance, phosim instance, phosim centroid, and so code includes treatment of lens sprinkling, SNe, and OpSim) (Authors: @rbiswas4  @jbkalmbach )
  - [`bin/generatePhosimInput`](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/bin/generatePhosimInput.py)
  - [`twinkles_sky`](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/python/desc/twinkles/twinkles_sky.py)
    - [`sprinkler`](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/python/desc/twinkles/sprinkler.py)
    - [`twinklesCatalogDefs`](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/python/desc/twinkles/twinklesCatalogDefs.py)
    - [`twinklesVariabilityMixins`](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/python/desc/twinkles/twinklesVariabilityMixins.py)
    - [`Methodology to Obtain SN params`](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/sn_inputs/examples/notebooks/ObtainingSNParams.ipynb)

---
- [x] PhoSim pipeline tasks and configuration files, including default values, plus test image results (Author: @TomGlanzman )
  - Run 3 PhoSim Production report issue thread (with plots) #369
  - [Tom's Google Doc write-up](https://docs.google.com/document/d/1hW5yEw5okpMeyYU_15QXvVOWuC6wzeJX3l54lKG2djM/edit)

---
- [ ] DM Level 2 Cookbook Recipe (still without image differencing, for now) (Author: @SimonKrughoff )
  - _link_

---
- [ ] DM Level 2 pipeline tasks and configuration files (Author: @tony-johnson )
  - _link_
  - _link_

---

---

*_How long should we assign to this important review meeting? *_ An hour in person might be enough, especially if some work has been done offline first.

**Who needs to be at the review?** @rbiswas4 @jchiang87 and @TomGlanzman can represent the coding, while @drphilmarshall, @SimonKrughoff , @jchiang87  and @sethdigel could act as reviewers. @danielsf , @jbkalmbach , and @tony-johnson  can help by providing links to the pipeline materials, which must all be up to date and ready to run.

**Comment by drphilmarshall** [comment]
Alright: it does look like we'll be able to do our Twinkles Run 3 Pipeline Review on Thursday October 20, when Tom is back from SF. Time is TBD #331 . Can you please take a look at the checklist at the top of this issue thread and edit it with links to your contributions? Thanks!

**Comment by jbkalmbach** [comment]
Should we make a new checklist based upon what we discussed at today's meeting?

**Comment by drphilmarshall** [comment]
Sure - but let's not make a new one, we can just edit the top comment in
this thread until it looks the way we want it to. You can treat everything
in there as mere starting points.

**Comment by drphilmarshall** [comment]
I added links to Tom's report (#369) to the checklist. Looks like we have everything linked now except the DM Level 2 Cookbook recipe and corresponding workflow scripts.
