### ISSUE TITLE
Create Strong Lensing Pipeline Review Notebook

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/Twinkles#364]
For the pipeline we want a strong lensing notebook that goes through several things:
- [ ] Explain Sprinkler
- [ ] Compare positions of lens images in Twinkles Instance Catalogs with positions from OM10 catalog
- [ ] Plot magnitude distributions, radial size and redshifts of lens galaxies in instance catalogs
- [ ] Plot magnitude distributions and redshifts of lensed AGN images in instance catalogs (Use brightest AGN image in a set)
- [ ] Check that variability is present in lensed AGN images in instance catalogs

**Comment by jbkalmbach** [comment]
@drphilmarshall These are what I had in my notes from today's meeting, but if I'm missing things please add them.

**Comment by drphilmarshall** [comment]
Looks good to me. Later we will need to explain how the sprinkler works: if it makes sense to do that now, please do go ahead and extend the checklist! Also, if you open the PR early I'll follow along and provide commentary as you push.

**Comment by jbkalmbach** [comment]
Merged in #371
