### ISSUE TITLE
Generate an updated catalog of host galaxies of the source AGNs

### ISSUE THREAD

**Issue by linan7788626** [LSSTDESC/Twinkles#443]
Hi @jbkalmbach ,

As you suggested, I create this issue for the discussion on how to generate an updated catalogs of host galaxies of the source AGNs for the Twinkles. Here are my ideas:

- [x] Picking out the 0th-image of the lensed AGNs from each Twinkles systems, and by matching TwinkleIDs with the lensing systems in OM10, we have the source positions (y1, y2) and the magnifications of this 0th-image AGNs. 
- [ ] The intrinsic magnitudes of the source AGNs then can be calculated following: mag_src = mag_lensed_AGN - 2.5 log10(1/magnification). 
- [ ] Based on the current positions and magnitudes, you can generate the host galaxies based on these sources. 

I am not sure whether above ideas make sense to you. The approach here should make more sense than that before. I have finished the first step, and you can find the filtered sprinkled AGNs [here](https://github.com/linan7788626/hack_with_Matt/blob/master/amatching_for_twinkles/twinkles_DESC_SLAC/filter_0_sprinkled_AGNs.txt). 

Before I implement the second step, I would like to ask two questions to you:
-  Do you think the equation in the second step is correct? 
- Whether the intrinsic magnitudes of the source AGNs are helpful for you to generate the host galaxies? 

Matt @mpwiesner and I have connected our matching codes and ray-tracing codes together, so if you could produce an updated catalog of host galaxies according to properties of source AGNs, it can not be better. Then, we can make significant progress during the HackWeek in Chicago. 

Should you have any questions or suggestions, please feel free to let me know.

Thank you so much!

All the best,
Nan

**Comment by linan7788626** [comment]
### Tasks list of the HackWeek Project at Fermilab

Hackers : @linan7788626, @mpwiesner, @jbkalmbach, @drphilmarshall, @bnord

This project is following the hackday project in the DESC meeting at SLAC. We are going to produce lensed host galaxies based one the catalogs we created in the hackday. The goal of this work is ***generating lensed host galaxies for lensed AGNs***, which is a preparation for the next stage of the Twinkles simulation. 

The basic idea is:
>Create a one-to-one relation between the 0th lensed AGN and the other components of the Twinkle systems.

![lensing_steps 001](https://cloud.githubusercontent.com/assets/1016652/24560049/9613a3bc-1606-11e7-9ea5-25384fdb617e.jpeg)

- [ ] Create the lensed host galaxies for the sprinkled AGNs in [this catalog](https://github.com/linan7788626/hack_with_Matt/blob/master/amatching_for_twinkles/twinkles_DESC_SLAC/sprinkled_agn_230.txt).

- [ ] Create an instance catalog of the images of lens galaxies for PhoSim by extracting information in [this catalog](https://github.com/linan7788626/hack_with_Matt/blob/master/amatching_for_twinkles/twinkles_DESC_SLAC/sprinkled_lens_galaxies_230.txt)

- [ ] If we have time, we will feed the instance catalogs of lensed AGNs, lens galaxies, and lensed host galaxies into PhoSim to Create a more realistic mock image for Twinkles. The field of view would be the same as that covered by the sprinkled AGNs in [the catalog above](https://github.com/linan7788626/hack_with_Matt/blob/master/amatching_for_twinkles/twinkles_DESC_SLAC/sprinkled_agn_230.txt).

### Inputs

- sprinkled_agn_230.txt
    - AGN_IDs, Twinkle_IDs, and other properties of the lensed AGNs...

- sprinkled_agn_230_catids.txt
    - CatSim_IDs (for seeking the corresponding host galaxies).

- sprinkled_lens_galaxies_230.txt
    - All the parameters of the images of lens galaxies.

- sprinkled_hosts_230.txt
    - All the parameters of the host galaxies, including multiple components.

- twinkles_lenses_v2.fits
    - Details of the mass model of the twinkle systems, the positions and magnifications of source AGNs.

### Output

- host_cat = (x1, x2, mag, Reff_a, Reff_b, zl, ndex, SED, AGN_ID, CatSim_ID)
- lens_cat = (x1, x2, vd, ql, phl, zl, AGN_ID, Twinkle_ID)
- lens_gal_cat = (y1, y2, mag, Reff_a, Reff_b, zs, ndex, SED, AGN_ID, Twinkle_ID)
- lensed_hosts_cat
    - Fits file as a 2d histogram for shooting photos in PhoSim
    - [AGN_ID] _[lens_ra]_[lens_dec]_ [mag] _ [SED] _ [zs] _ [PixelSize] . fits

**Comment by drphilmarshall** [comment]
Rock. ON. This is going to be great! Let's try hard to get the PhoSim outputs in place: I really want to see how visible these host galaxies are, by eye, preferably by blinking back and forth between two _gri_ color composite cutout image PNGs :-) Even if we don't get that far, a key aspect of this project is visualization: let's display the different components of the cutout image as we make them, to check that we are building up sensible things. This will also work best if we use _gri_ composites, always with the same cutout field of view and the same color scales and nonlinearity. We have code to make these, [`HumVI`](https://github.com/drphilmarshall/HumVI), but it will need upgrading to work with the LSST/PhoSim/whatever format headers that our FITS files have.

**Comment by linan7788626** [comment]
Hi @drphilmarshall 

Thank you for your suggestion. Yes, you are right, let's try to get the PhoSim outputs first. We all are interested in the visibility of the lensed host galaxies, but we may go further if there is enough time. :-). 

Regardless, this is just the first version of the task list, if you would like to update it with your ideas and suggestions, I really appreciate it. Looking forward to meeting you at Fermilab next week. :-)

Best,
Nan

**Comment by jbkalmbach** [comment]
Hi @linan7788626 here is an updated version of sprinkled_hosts_230.txt with no magnification in the AGN hosts. It was created using the notebook I made and am merging shortly.

[sprinkled_hosts_230.txt](https://github.com/LSSTDESC/Twinkles/files/891376/sprinkled_hosts_230.txt)

**Comment by linan7788626** [comment]
Hi, @jbkalmbach, thank you for the updated catalog, it is very helpful. I am working on wrapping up all the codes for this project and will post the updates here tomorrow.

**Comment by jbkalmbach** [comment]
[sprinkled_agn_230.txt](https://github.com/LSSTDESC/Twinkles/files/891480/sprinkled_agn_230.txt)
[sprinkled_lens_galaxies_230.txt](https://github.com/LSSTDESC/Twinkles/files/891481/sprinkled_lens_galaxies_230.txt)

Here are updated agn and lens catalogs as well. You can match the AGN and the AGN hosts to the lens using `lens_galaxy_uID` column.

**Comment by linan7788626** [comment]
Fantastic, Thanks a lot.

**Comment by linan7788626** [comment]
Hi @mpwiesner,

Please check out these files from Bryce:

[sprinkled_agn_230.txt](https://github.com/LSSTDESC/Twinkles/files/891480/sprinkled_agn_230.txt)
[sprinkled_lens_galaxies_230.txt](https://github.com/LSSTDESC/Twinkles/files/891481/sprinkled_lens_galaxies_230.txt)

0. We plan to feed the instance catalogs into PhoSim in three steps:
    - Lensed AGNs
    - image of lens galaxies
    - lensed host galaxies

1. You can find all the parameters you need for creating the instance catalogs of lensed AGNs and lens galaxies for PhoSim. Let's create these instance catalogs first.

2. I have obtained all the fits files and needed parameters for creating the instance catalogs of lensed host galaxies. Please let me know when you are ready for this, then I will point you to the data.

Thanks,
Nan

**Comment by mpwiesner** [comment]
@linan7788626 and @jbkalmbach this looks great.  I can easily take these all and make instance files and run PhoSim.  Is it correct that our end goal is 199 individual FITS images, one for each lensing system?

**Comment by linan7788626** [comment]
Hi, @mpwiesner , in my opinion, the end goal is not 199 individual FITS images, but a patch of the sky including all the Twinkle systems. Probably, it would be similar to the sample picture in the description of Twinkles. 

Hi @jbkalmbach and @drphilmarshall , could you please confirm the end products of this hackweek is 199 individual FITS images or a patch of the sky including 199 twinkles system? Thank you so much!

Best,
Nan

**Comment by drphilmarshall** [comment]
I'd say go for the sensor image - we can make cutout images later. But
either works - do whatever is fastest and easiest! :-)

**Comment by mpwiesner** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14111037/24799945/9e954baa-1b63-11e7-8b24-3b0263f56ada.png)
Here is an image of a lensing system at (53.065667, -27.479433), output by PhoSim.  Left is images of AGN and lensing galaxy.  Right also includes the lensed host.  We now have many of these, this is just a sample.

**Comment by linan7788626** [comment]
Hi @mpwiesner , the new images are good, but we need to double check something first. 

- Left Image:
    - Is blue one lensed AGN?
    - Is there only one lensed AGN?
    - Is the yellow ball the image of lens galaxy? 
    - Is another lensed AGN obstructed by the lens galaxy?

- Right Image: 
    - The relative positions of the lensed hosts to the lens galaxy are reasonable to me.
    - However, there is a considerable offset between the lensed AGNs and lensed hosts, and this might be the issue mentioned by @drphilmarshall yesterday. But It could be because of the incorrect position of the lens galaxy. Did you obtain the position of lens galaxy from this catalog [sprinkled_lens_galaxies_230.txt](https://github.com/LSSTDESC/Twinkles/files/891481/sprinkled_lens_galaxies_230.txt)? I did not found a lens galaxy at (53.065667, -27.479433). 

In my opionion, the critical issue in current results is that Making sure the locations of lensed AGNs and lens galaxies are correct.  If you could give me any details, it should be awesome. 

Thanks,
Nan

**Comment by mpwiesner** [comment]
![99](https://cloud.githubusercontent.com/assets/14111037/24809550/7a4bfb96-1b85-11e7-8bb1-9c0bcd368b3d.png)
One more of the several hundred images we made, this one at ( 52.920242, -27.427762).
